# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pangram_game.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='pangram_game.proto',
  package='app',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x12pangram_game.proto\x12\x03\x61pp\"3\n\x0bGameRequest\x12\x12\n\nplayerName\x18\x01 \x01(\t\x12\x10\n\x08gameType\x18\x02 \x01(\t\"\x1e\n\x0cGameResponse\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"\"\n\x10StartGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"$\n\x11StartGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"6\n\x10\x43heckWordRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\x12\x12\n\nplayerWord\x18\x02 \x01(\t\"H\n\x11\x43heckWordResponse\x12\x19\n\x11gameStatusMessage\x18\x01 \x01(\t\x12\x18\n\x10wordCheckMessage\x18\x02 \x01(\t\"!\n\x0fJoinGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"#\n\x10JoinGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\"\"\n\x10LeaveGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"$\n\x11LeaveGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t\" \n\x0e\x45ndGameRequest\x12\x0e\n\x06gameId\x18\x01 \x01(\x0c\"\"\n\x0f\x45ndGameResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2\xef\x02\n\x0bPangramGame\x12\x33\n\nCreateGame\x12\x10.app.GameRequest\x1a\x11.app.GameResponse\"\x00\x12<\n\tStartGame\x12\x15.app.StartGameRequest\x1a\x16.app.StartGameResponse\"\x00\x12<\n\tCheckWord\x12\x15.app.CheckWordRequest\x1a\x16.app.CheckWordResponse\"\x00\x12\x39\n\x08JoinGame\x12\x14.app.JoinGameRequest\x1a\x15.app.JoinGameResponse\"\x00\x12<\n\tLeaveGame\x12\x15.app.LeaveGameRequest\x1a\x16.app.LeaveGameResponse\"\x00\x12\x36\n\x07\x45ndGame\x12\x13.app.EndGameRequest\x1a\x14.app.EndGameResponse\"\x00\x62\x06proto3'
)




_GAMEREQUEST = _descriptor.Descriptor(
  name='GameRequest',
  full_name='app.GameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='playerName', full_name='app.GameRequest.playerName', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='app.GameRequest.gameType', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=78,
)


_GAMERESPONSE = _descriptor.Descriptor(
  name='GameResponse',
  full_name='app.GameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.GameResponse.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=110,
)


_STARTGAMEREQUEST = _descriptor.Descriptor(
  name='StartGameRequest',
  full_name='app.StartGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.StartGameRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=112,
  serialized_end=146,
)


_STARTGAMERESPONSE = _descriptor.Descriptor(
  name='StartGameResponse',
  full_name='app.StartGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='app.StartGameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=148,
  serialized_end=184,
)


_CHECKWORDREQUEST = _descriptor.Descriptor(
  name='CheckWordRequest',
  full_name='app.CheckWordRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.CheckWordRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='playerWord', full_name='app.CheckWordRequest.playerWord', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=186,
  serialized_end=240,
)


_CHECKWORDRESPONSE = _descriptor.Descriptor(
  name='CheckWordResponse',
  full_name='app.CheckWordResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameStatusMessage', full_name='app.CheckWordResponse.gameStatusMessage', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='wordCheckMessage', full_name='app.CheckWordResponse.wordCheckMessage', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=242,
  serialized_end=314,
)


_JOINGAMEREQUEST = _descriptor.Descriptor(
  name='JoinGameRequest',
  full_name='app.JoinGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.JoinGameRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=349,
)


_JOINGAMERESPONSE = _descriptor.Descriptor(
  name='JoinGameResponse',
  full_name='app.JoinGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='app.JoinGameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=386,
)


_LEAVEGAMEREQUEST = _descriptor.Descriptor(
  name='LeaveGameRequest',
  full_name='app.LeaveGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.LeaveGameRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=388,
  serialized_end=422,
)


_LEAVEGAMERESPONSE = _descriptor.Descriptor(
  name='LeaveGameResponse',
  full_name='app.LeaveGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='app.LeaveGameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=460,
)


_ENDGAMEREQUEST = _descriptor.Descriptor(
  name='EndGameRequest',
  full_name='app.EndGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='gameId', full_name='app.EndGameRequest.gameId', index=0,
      number=1, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=462,
  serialized_end=494,
)


_ENDGAMERESPONSE = _descriptor.Descriptor(
  name='EndGameResponse',
  full_name='app.EndGameResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='message', full_name='app.EndGameResponse.message', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=496,
  serialized_end=530,
)

DESCRIPTOR.message_types_by_name['GameRequest'] = _GAMEREQUEST
DESCRIPTOR.message_types_by_name['GameResponse'] = _GAMERESPONSE
DESCRIPTOR.message_types_by_name['StartGameRequest'] = _STARTGAMEREQUEST
DESCRIPTOR.message_types_by_name['StartGameResponse'] = _STARTGAMERESPONSE
DESCRIPTOR.message_types_by_name['CheckWordRequest'] = _CHECKWORDREQUEST
DESCRIPTOR.message_types_by_name['CheckWordResponse'] = _CHECKWORDRESPONSE
DESCRIPTOR.message_types_by_name['JoinGameRequest'] = _JOINGAMEREQUEST
DESCRIPTOR.message_types_by_name['JoinGameResponse'] = _JOINGAMERESPONSE
DESCRIPTOR.message_types_by_name['LeaveGameRequest'] = _LEAVEGAMEREQUEST
DESCRIPTOR.message_types_by_name['LeaveGameResponse'] = _LEAVEGAMERESPONSE
DESCRIPTOR.message_types_by_name['EndGameRequest'] = _ENDGAMEREQUEST
DESCRIPTOR.message_types_by_name['EndGameResponse'] = _ENDGAMERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GameRequest = _reflection.GeneratedProtocolMessageType('GameRequest', (_message.Message,), {
  'DESCRIPTOR' : _GAMEREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.GameRequest)
  })
_sym_db.RegisterMessage(GameRequest)

GameResponse = _reflection.GeneratedProtocolMessageType('GameResponse', (_message.Message,), {
  'DESCRIPTOR' : _GAMERESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.GameResponse)
  })
_sym_db.RegisterMessage(GameResponse)

StartGameRequest = _reflection.GeneratedProtocolMessageType('StartGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _STARTGAMEREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.StartGameRequest)
  })
_sym_db.RegisterMessage(StartGameRequest)

StartGameResponse = _reflection.GeneratedProtocolMessageType('StartGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _STARTGAMERESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.StartGameResponse)
  })
_sym_db.RegisterMessage(StartGameResponse)

CheckWordRequest = _reflection.GeneratedProtocolMessageType('CheckWordRequest', (_message.Message,), {
  'DESCRIPTOR' : _CHECKWORDREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.CheckWordRequest)
  })
_sym_db.RegisterMessage(CheckWordRequest)

CheckWordResponse = _reflection.GeneratedProtocolMessageType('CheckWordResponse', (_message.Message,), {
  'DESCRIPTOR' : _CHECKWORDRESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.CheckWordResponse)
  })
_sym_db.RegisterMessage(CheckWordResponse)

JoinGameRequest = _reflection.GeneratedProtocolMessageType('JoinGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _JOINGAMEREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.JoinGameRequest)
  })
_sym_db.RegisterMessage(JoinGameRequest)

JoinGameResponse = _reflection.GeneratedProtocolMessageType('JoinGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _JOINGAMERESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.JoinGameResponse)
  })
_sym_db.RegisterMessage(JoinGameResponse)

LeaveGameRequest = _reflection.GeneratedProtocolMessageType('LeaveGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _LEAVEGAMEREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.LeaveGameRequest)
  })
_sym_db.RegisterMessage(LeaveGameRequest)

LeaveGameResponse = _reflection.GeneratedProtocolMessageType('LeaveGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEAVEGAMERESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.LeaveGameResponse)
  })
_sym_db.RegisterMessage(LeaveGameResponse)

EndGameRequest = _reflection.GeneratedProtocolMessageType('EndGameRequest', (_message.Message,), {
  'DESCRIPTOR' : _ENDGAMEREQUEST,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.EndGameRequest)
  })
_sym_db.RegisterMessage(EndGameRequest)

EndGameResponse = _reflection.GeneratedProtocolMessageType('EndGameResponse', (_message.Message,), {
  'DESCRIPTOR' : _ENDGAMERESPONSE,
  '__module__' : 'pangram_game_pb2'
  # @@protoc_insertion_point(class_scope:app.EndGameResponse)
  })
_sym_db.RegisterMessage(EndGameResponse)



_PANGRAMGAME = _descriptor.ServiceDescriptor(
  name='PangramGame',
  full_name='app.PangramGame',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=533,
  serialized_end=900,
  methods=[
  _descriptor.MethodDescriptor(
    name='CreateGame',
    full_name='app.PangramGame.CreateGame',
    index=0,
    containing_service=None,
    input_type=_GAMEREQUEST,
    output_type=_GAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='StartGame',
    full_name='app.PangramGame.StartGame',
    index=1,
    containing_service=None,
    input_type=_STARTGAMEREQUEST,
    output_type=_STARTGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='CheckWord',
    full_name='app.PangramGame.CheckWord',
    index=2,
    containing_service=None,
    input_type=_CHECKWORDREQUEST,
    output_type=_CHECKWORDRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='JoinGame',
    full_name='app.PangramGame.JoinGame',
    index=3,
    containing_service=None,
    input_type=_JOINGAMEREQUEST,
    output_type=_JOINGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='LeaveGame',
    full_name='app.PangramGame.LeaveGame',
    index=4,
    containing_service=None,
    input_type=_LEAVEGAMEREQUEST,
    output_type=_LEAVEGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='EndGame',
    full_name='app.PangramGame.EndGame',
    index=5,
    containing_service=None,
    input_type=_ENDGAMEREQUEST,
    output_type=_ENDGAMERESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_PANGRAMGAME)

DESCRIPTOR.services_by_name['PangramGame'] = _PANGRAMGAME

# @@protoc_insertion_point(module_scope)
