# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import pangram_game_pb2 as pangram__game__pb2


class PangramGameStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateGame = channel.unary_unary(
                '/app.PangramGame/CreateGame',
                request_serializer=pangram__game__pb2.GameRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.GameResponse.FromString,
                )
        self.StartGame = channel.unary_unary(
                '/app.PangramGame/StartGame',
                request_serializer=pangram__game__pb2.StartGameRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.StartGameResponse.FromString,
                )
        self.JoinGame = channel.unary_unary(
                '/app.PangramGame/JoinGame',
                request_serializer=pangram__game__pb2.JoinGameRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.JoinGameResponse.FromString,
                )
        self.CheckWord = channel.unary_unary(
                '/app.PangramGame/CheckWord',
                request_serializer=pangram__game__pb2.CheckWordRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.CheckWordResponse.FromString,
                )
        self.GameScore = channel.unary_unary(
                '/app.PangramGame/GameScore',
                request_serializer=pangram__game__pb2.GameScoreRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.GameScoreResponse.FromString,
                )
        self.LeaveGame = channel.unary_unary(
                '/app.PangramGame/LeaveGame',
                request_serializer=pangram__game__pb2.LeaveGameRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.LeaveGameResponse.FromString,
                )
        self.EndGame = channel.unary_unary(
                '/app.PangramGame/EndGame',
                request_serializer=pangram__game__pb2.EndGameRequest.SerializeToString,
                response_deserializer=pangram__game__pb2.EndGameResponse.FromString,
                )


class PangramGameServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def JoinGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CheckWord(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GameScore(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def LeaveGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def EndGame(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PangramGameServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateGame': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateGame,
                    request_deserializer=pangram__game__pb2.GameRequest.FromString,
                    response_serializer=pangram__game__pb2.GameResponse.SerializeToString,
            ),
            'StartGame': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGame,
                    request_deserializer=pangram__game__pb2.StartGameRequest.FromString,
                    response_serializer=pangram__game__pb2.StartGameResponse.SerializeToString,
            ),
            'JoinGame': grpc.unary_unary_rpc_method_handler(
                    servicer.JoinGame,
                    request_deserializer=pangram__game__pb2.JoinGameRequest.FromString,
                    response_serializer=pangram__game__pb2.JoinGameResponse.SerializeToString,
            ),
            'CheckWord': grpc.unary_unary_rpc_method_handler(
                    servicer.CheckWord,
                    request_deserializer=pangram__game__pb2.CheckWordRequest.FromString,
                    response_serializer=pangram__game__pb2.CheckWordResponse.SerializeToString,
            ),
            'GameScore': grpc.unary_unary_rpc_method_handler(
                    servicer.GameScore,
                    request_deserializer=pangram__game__pb2.GameScoreRequest.FromString,
                    response_serializer=pangram__game__pb2.GameScoreResponse.SerializeToString,
            ),
            'LeaveGame': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaveGame,
                    request_deserializer=pangram__game__pb2.LeaveGameRequest.FromString,
                    response_serializer=pangram__game__pb2.LeaveGameResponse.SerializeToString,
            ),
            'EndGame': grpc.unary_unary_rpc_method_handler(
                    servicer.EndGame,
                    request_deserializer=pangram__game__pb2.EndGameRequest.FromString,
                    response_serializer=pangram__game__pb2.EndGameResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'app.PangramGame', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class PangramGame(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/CreateGame',
            pangram__game__pb2.GameRequest.SerializeToString,
            pangram__game__pb2.GameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/StartGame',
            pangram__game__pb2.StartGameRequest.SerializeToString,
            pangram__game__pb2.StartGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def JoinGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/JoinGame',
            pangram__game__pb2.JoinGameRequest.SerializeToString,
            pangram__game__pb2.JoinGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CheckWord(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/CheckWord',
            pangram__game__pb2.CheckWordRequest.SerializeToString,
            pangram__game__pb2.CheckWordResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GameScore(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/GameScore',
            pangram__game__pb2.GameScoreRequest.SerializeToString,
            pangram__game__pb2.GameScoreResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def LeaveGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/LeaveGame',
            pangram__game__pb2.LeaveGameRequest.SerializeToString,
            pangram__game__pb2.LeaveGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def EndGame(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/app.PangramGame/EndGame',
            pangram__game__pb2.EndGameRequest.SerializeToString,
            pangram__game__pb2.EndGameResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
